mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    #path('paqs/', include(('paqs.urls', 'paqs'), namespace='paqs')),
    path('', include(('paqs.urls', 'paqs'), namespace='paqs')),    
]

paqs/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views


#PAQs App

urlpatterns = [
    path('', views.index, name=''),
    path('backpaq', views.backpaq, name='backpaq'),
    path('headachepaq', views.headachepaq, name='headachepaq'),
    path('gerdpaq', views.gerdpaq, name='gerdpaq'),
]

paqs/models.py
from django.db import models

#from main.models import Account
from .constants import PAQ_NAME_CHOICES

# Create your models here.

class PAQ(models.Model):
    name = models.CharField(max_length=50, choices=PAQ_NAME_CHOICES, unique=True)
    #user = models.OneToOneField(Account, on_delete=models.CASCADE)
    paq_record = models.CharField(max_length=255,default=None,null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

paqs/views.py
from audioop import reverse
from base64 import encode
from dis import Instruction
from operator import truediv
from random import randint
from django.shortcuts import redirect, render
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.views import View
import pdfrw
from django.core.files import File
#from azure.storage.blob import BlobServiceClient, BlobClient, ContainerClient, __version__
from paqs.utils import process_paq
#from . import nonsql
import json
import os
from .models import *
from django.contrib.auth.decorators import login_required
from django.conf import settings
#from calculator.models import User_PAQs, Disabilities
#from products.models import Products
from .mapping.headache import mapHeadache
from .mapping.GERD import mapGERD
#from products.models import Product_per_client
#from .includeProduct import addPAQtoCart as addPAQtoCart

#from main.models import IAQ
from.constants import PAQ_NAME_CHOICES

from .utils import dbq_generator

def index(request):
    return HttpResponse("hello! Make sure you change the URL to point to the PAQ you are working with")

def backpaq(request):
    return process_paq(request, PAQ_NAME_CHOICES[2], 'paqs/back_paq.html', None, 'Back - Spine', 'back_mazi')

def headachepaq(request):
    return process_paq(request, PAQ_NAME_CHOICES[15], 'paqs/headache_paq.html', mapHeadache, 'Headache (Migraines)', 'headaches')

def gerdpaq(request):
    return process_paq(request, PAQ_NAME_CHOICES[12], 'paqs/gerd.html', mapGERD, 'GERD', 'GERD')

paqs/templates/paqs/paqs.html
{% extends 'main/dashboard/dashboard.html' %}
{% load static %}

{% block title %}PAQS{% endblock title %}

{% block dashboard %}
{%if message%}
<div class="alert alert-success" role="alert">
  <p class="mb-0">{{message}}</p>
  <br>
  <p class="mb-0">We can Help you increase your disability rating with the next disabilities:</p>
  <br>
  {%for PAQ in PAQS%}
  <p class="mb-0"> • {{PAQ}}</p>
  {%endfor%}
</div>
{%endif%}
<h1 class="mb-5 text-center">
  <u>PAQs</u>
</h1>

{% comment %} <div class="row">
  <div class="col-sm-6">
    <div class="card">
      <div class="card-body">
        <h5 class="card-title">Back PAQ</h5>
        <p class="card-text">Personal Assessment Questionnaire</p>
        <a href="{%url 'paqs:backpaq'%}" class="btn btn-primary">Back PAQ</a>
      </div>
    </div>
  </div>
  <div class="col-sm-6">
    <div class="card">
      <div class="card-body">
        <h5 class="card-title">Mental PAQ</h5>
        <p class="card-text">Personal Assessment Questionnaire</p>
        <a href="{%url 'paqs:headachepaq'%}" class="btn btn-primary">Other PAQ</a>
      </div>
    </div>
  </div>
</div>


<div class="row"><br><br><br><br></div>
<div class="row"><hr></div>
<div class="row"><br><br><br><br></div> {% endcomment %}

<div class="row">
{%for dis in dis_data%}
  <div class="col-sm-6">
    <div class="card">
      <div class="card-body">
        {%if dis.url == 'paqs:paqs'%}
          <h5 class="card-title" disabled>{{dis.disability}} - (Coming soon)</h5>
          <p>Currently, we do not offer a PAQ for this DBQ.</p> 
          <p>However, it is in our plans. We'll notify as soon as we offer it.</p>
          <p class="card-text" disabled>Personal Assessment Questionnaire</p>
          <a href="{%url dis.url %}" class="btn btn-primary disabled">{{dis.disability}}</a>
          {%else%}
          <h5 class="card-title">{{dis.disability}}</h5>
          <p class="card-text">Personal Assessment Questionnaire</p>
          <a href="{%url dis.url %}" class="btn btn-primary">{{dis.disability}}</a>
        {%endif%}
      </div>
    </div>
  </div>
{%endfor%}
</div>

{%if offerPaq == 0%}
<div class="row">
  <div class="row g-3 d-flex justify-content-center">
    <p class="text-center">PAQs to DBQs without completing ({{offerPaq}})</p>
    <p class="text-center">Seems like there is no more PAQs to complete</p>
    <a type="button"
    class="btn btn-success col-sm-12 col-md-12 col-lg-6"
    >
    Pay now!
  </a> 
  {%comment%}
  I could pull one more variable and check if they have something in the cart. There, we decide if the button says
  Pay or something else
  {% endcomment %}
</div>
<br>
</div>
{%endif%}

{% comment %} <div class="row">
</br>
</br>
</div>
<div class="row">
  <div class="col-sm-6">
    <div class="card">
      <div class="card-body">
        <h5 class="card-title">Other PAQ</h5>
        <p class="card-text">Personal Assessment Questionnaire</p>
        <a href="#" class="btn btn-primary">Other PAQ</a>
      </div>
    </div>
  </div>
  <div class="col-sm-6">
    <div class="card">
      <div class="card-body">
        <h5 class="card-title">Other PAQ</h5>
        <p class="card-text">Personal Assessment Questionnaire</p>
        <a href="#" class="btn btn-primary">Other PAQ</a>
      </div>
    </div>
  </div>
</div>

<div class="row">
</br>
</br>
</br>
</br>
</div>

<div class="col-lg-4 col-md-6 col-12" style="display:none">
        <form id="iaq-form"
              method="POST"
              enctype="multipart/form-data"
              autocomplete="off">
            {% csrf_token %}
            <div class="form-group">
                <label for="name">Legal Name:</label>
                <input type="text"
                       class="form-control"
                       id="name"
                       name="name"
                       aria-describedby="nameHelp"
                       placeholder="Enter your legal name">
                <small id="nameHelp" class="form-text text-muted">Please enter your name as it shows in your DD-214</small>
            </div>
            <br>
            <div class="form-group">
                <label for="ssn">SSN:</label>
                <input type="password"
                       class="form-control"
                       id="ssn"
                       name="ssn"
                       aria-describedby="ssnHelp"
                       placeholder="Enter SSN"
                       minlength="9"
                       maxlength="12">
                <small id="passwordHelp" class="form-text text-muted">We consider this very private information</small>
            </div>
            <br>
            <button type="submit" class="btn btn-primary">Submit</button>
        </form>
    </div> {% endcomment %}
    <!--<button type="submit" class="btn btn-primary">Submit</button>-->
    <div class="row">
      <div class="row g-3 d-flex justify-content-center">
        <a type="button"
        class="btn btn-danger col-sm-12 col-md-12 col-lg-6"
        id='seehelp'
        disabled
        href="#"
        >
        Something in my disabilities looks off, and I'd like to change it
      </a>
    </div>
    <br>
  </div>
{% endblock dashboard %}

paqs/templates/paqs/thankyou.html
{% extends 'main/dashboard/dashboard.html' %}
{% load static %}

 {% block dashboard %}
  <div class="col-lg-4 col-md-6 col-12">
    <h1 class="mb-5 text-center"><u>Thank you, {{name}}</u></h1>
  </div> 
 {% endblock dashboard %}